// 新增题库（v4 扩充）：与旧题库合并使用
module.exports = [
  // ========== Git 版本控制 ==========
  { type: 'cmd', answers: ['git'], meaning: '分布式版本控制工具', en: 'Git', cat: 'Git 版本控制', usage: 'git clone <仓库地址>' },
  { type: 'cmd', answers: ['git init'], meaning: '初始化本地仓库', en: 'initialize', cat: 'Git 版本控制', usage: 'git init' },
  { type: 'cmd', answers: ['git clone'], meaning: '克隆远程仓库到本地', en: 'clone', cat: 'Git 版本控制', usage: 'git clone https://github.com/user/repo.git' },
  { type: 'cmd', answers: ['git add'], meaning: '把更改加入暂存区', en: 'add', cat: 'Git 版本控制', usage: 'git add 文件名' },
  { type: 'cmd', answers: ['git commit'], meaning: '提交暂存区为一次版本', en: 'commit', cat: 'Git 版本控制', usage: 'git commit -m "修复 bug"' },
  { type: 'cmd', answers: ['git push'], meaning: '推送本地提交到远程', en: 'push', cat: 'Git 版本控制', usage: 'git push origin main' },
  { type: 'cmd', answers: ['git pull'], meaning: '拉取远程更新并合并', en: 'pull', cat: 'Git 版本控制', usage: 'git pull' },
  { type: 'cmd', answers: ['git fetch'], meaning: '获取远程更新（不合并）', en: 'fetch', cat: 'Git 版本控制', usage: 'git fetch origin' },
  { type: 'cmd', answers: ['git merge'], meaning: '合并分支', en: 'merge', cat: 'Git 版本控制', usage: 'git merge feature' },
  { type: 'cmd', answers: ['git rebase'], meaning: '变基（重放提交）', en: 'rebase', cat: 'Git 版本控制', usage: 'git rebase main' },
  { type: 'cmd', answers: ['git branch'], meaning: '查看/创建分支', en: 'branch', cat: 'Git 版本控制', usage: 'git branch dev' },
  { type: 'cmd', answers: ['git checkout'], meaning: '切换分支/恢复文件', en: 'checkout', cat: 'Git 版本控制', usage: 'git checkout dev' },
  { type: 'cmd', answers: ['git switch'], meaning: '切换分支（新命令）', en: 'switch', cat: 'Git 版本控制', usage: 'git switch -c 新分支' },
  { type: 'cmd', answers: ['git status'], meaning: '查看工作区状态', en: 'status', cat: 'Git 版本控制', usage: 'git status' },
  { type: 'cmd', answers: ['git log'], meaning: '查看提交历史', en: 'log', cat: 'Git 版本控制', usage: 'git log --oneline' },
  { type: 'cmd', answers: ['git diff'], meaning: '查看工作区差异', en: 'diff', cat: 'Git 版本控制', usage: 'git diff' },
  { type: 'cmd', answers: ['git stash'], meaning: '暂存未提交的更改', en: 'stash', cat: 'Git 版本控制', usage: 'git stash' },
  { type: 'cmd', answers: ['git remote'], meaning: '管理远程仓库', en: 'remote', cat: 'Git 版本控制', usage: 'git remote -v' },
  { type: 'cmd', answers: ['git tag'], meaning: '给提交打标签', en: 'tag', cat: 'Git 版本控制', usage: 'git tag v1.0.0' },
  { type: 'cmd', answers: ['git reset'], meaning: '回退版本/取消暂存', en: 'reset', cat: 'Git 版本控制', usage: 'git reset --hard HEAD~1' },
  { type: 'cmd', answers: ['git revert'], meaning: '用新提交撤销旧提交', en: 'revert', cat: 'Git 版本控制', usage: 'git revert HEAD' },
  { type: 'cmd', answers: ['git show'], meaning: '显示某次提交详情', en: 'show', cat: 'Git 版本控制', usage: 'git show HEAD' },

  // ========== 容器与云 ==========
  { type: 'cmd', answers: ['docker'], meaning: '容器引擎', en: 'docker', cat: '容器与云', usage: 'docker run -d nginx' },
  { type: 'cmd', answers: ['docker ps'], meaning: '列出运行中的容器', en: 'process status', cat: '容器与云', usage: 'docker ps -a' },
  { type: 'cmd', answers: ['docker run'], meaning: '运行一个容器', en: 'run', cat: '容器与云', usage: 'docker run -p 8080:80 nginx' },
  { type: 'cmd', answers: ['docker build'], meaning: '构建镜像', en: 'build', cat: '容器与云', usage: 'docker build -t myapp .' },
  { type: 'cmd', answers: ['docker images'], meaning: '列出本地镜像', en: 'images', cat: '容器与云', usage: 'docker images' },
  { type: 'cmd', answers: ['docker pull'], meaning: '拉取镜像', en: 'pull', cat: '容器与云', usage: 'docker pull ubuntu:22.04' },
  { type: 'cmd', answers: ['docker push'], meaning: '推送镜像到仓库', en: 'push', cat: '容器与云', usage: 'docker push user/myapp' },
  { type: 'cmd', answers: ['docker exec'], meaning: '进入运行中容器执行命令', en: 'execute', cat: '容器与云', usage: 'docker exec -it 容器ID bash' },
  { type: 'cmd', answers: ['docker logs'], meaning: '查看容器日志', en: 'logs', cat: '容器与云', usage: 'docker logs -f 容器ID' },
  { type: 'cmd', answers: ['docker-compose'], meaning: '多容器编排工具', en: 'compose', cat: '容器与云', usage: 'docker-compose up -d' },
  { type: 'cmd', answers: ['kubectl'], meaning: 'Kubernetes 命令行工具', en: 'kubernetes control', cat: '容器与云', usage: 'kubectl get pods' },
  { type: 'cmd', answers: ['helm'], meaning: 'K8s 应用包管理器', en: 'helm', cat: '容器与云', usage: 'helm install myapp chart' },
  { type: 'cmd', answers: ['podman'], meaning: '无守护进程的容器引擎', en: 'pod manager', cat: '容器与云', usage: 'podman run hello-world' },
  { type: 'cmd', answers: ['minikube'], meaning: '本地单节点 K8s', en: 'mini kube', cat: '容器与云', usage: 'minikube start' },

  // ========== Shell 技巧 ==========
  { type: 'cmd', answers: ['|'], meaning: '管道：前命令输出作后命令输入', en: 'pipe', cat: 'Shell 技巧', usage: 'cat a.txt | grep key' },
  { type: 'cmd', answers: ['>'], meaning: '重定向：覆盖写入文件', en: 'redirect', cat: 'Shell 技巧', usage: 'echo hi > out.txt' },
  { type: 'cmd', answers: ['>>'], meaning: '重定向：追加到文件末尾', en: 'append', cat: 'Shell 技巧', usage: 'echo hi >> log.txt' },
  { type: 'cmd', answers: ['<'], meaning: '重定向：从文件读取输入', en: 'input redirect', cat: 'Shell 技巧', usage: 'sort < list.txt' },
  { type: 'cmd', answers: ['2>'], meaning: '把错误输出重定向到文件', en: 'stderr redirect', cat: 'Shell 技巧', usage: 'cmd 2> error.log' },
  { type: 'cmd', answers: ['&'], meaning: '后台运行命令', en: 'background', cat: 'Shell 技巧', usage: 'sleep 100 &' },
  { type: 'cmd', answers: ['&&'], meaning: '前命令成功才执行后命令', en: 'AND operator', cat: 'Shell 技巧', usage: 'mkdir dir && cd dir' },
  { type: 'cmd', answers: ['||'], meaning: '前命令失败才执行后命令', en: 'OR operator', cat: 'Shell 技巧', usage: 'cd dir || echo 失败' },
  { type: 'cmd', answers: [';'], meaning: '顺序执行多条命令', en: 'semicolon', cat: 'Shell 技巧', usage: 'cd /tmp; ls' },
  { type: 'cmd', answers: ['*'], meaning: '通配符：匹配任意字符', en: 'wildcard', cat: 'Shell 技巧', usage: 'rm *.log' },
  { type: 'cmd', answers: ['?'], meaning: '通配符：匹配单个字符', en: 'question mark', cat: 'Shell 技巧', usage: 'ls a?.txt' },
  { type: 'cmd', answers: ['$()'], meaning: '命令替换：先执行再取结果', en: 'command substitution', cat: 'Shell 技巧', usage: 'echo 今天是 $(date)' },
  { type: 'cmd', answers: ['!'], meaning: '引用历史命令（!n / !!）', en: 'history reference', cat: 'Shell 技巧', usage: '!!' },
  { type: 'cmd', answers: ['~'], meaning: '家目录缩写', en: 'home directory', cat: 'Shell 技巧', usage: 'cd ~/Documents' },
  { type: 'cmd', answers: ['$?'], meaning: '上一条命令的退出码', en: 'exit status', cat: 'Shell 技巧', usage: 'echo $?' },
  { type: 'cmd', answers: ['$$'], meaning: '当前 Shell 的进程号', en: 'PID', cat: 'Shell 技巧', usage: 'echo $$' },

  // ========== 正则与数据处理 ==========
  { type: 'cmd', answers: ['rg'], meaning: '超快正则搜索（ripgrep）', en: 'ripgrep', cat: '正则与数据处理', usage: 'rg pattern src/' },
  { type: 'cmd', answers: ['jq'], meaning: 'JSON 数据处理工具', en: 'JSON query', cat: '正则与数据处理', usage: 'curl api | jq .name' },
  { type: 'cmd', answers: ['fzf'], meaning: '模糊查找选择器', en: 'fuzzy finder', cat: '正则与数据处理', usage: 'find . | fzf' },
  { type: 'cmd', answers: ['fmt'], meaning: '文本重新排版', en: 'format', cat: '正则与数据处理', usage: 'fmt -w 80 a.txt' },
  { type: 'cmd', answers: ['pr'], meaning: '分页格式化打印文件', en: 'print', cat: '正则与数据处理', usage: 'pr -2 a.txt' },
  { type: 'cmd', answers: ['hd'], meaning: '十六进制查看文件（hexdump 别名）', en: 'hex dump', cat: '正则与数据处理', usage: 'hd a.bin' },
  { type: 'cmd', answers: ['ag'], meaning: '代码全文搜索（silver searcher）', en: 'silver searcher', cat: '正则与数据处理', usage: 'ag keyword src' },
  { type: 'cmd', answers: ['yq'], meaning: 'YAML 数据处理工具', en: 'YAML query', cat: '正则与数据处理', usage: 'yq .spec a.yaml' },

  // ========== 编译与调试 ==========
  { type: 'cmd', answers: ['gcc'], meaning: 'GNU C 编译器', en: 'GNU C compiler', cat: '编译与调试', usage: 'gcc -o app main.c' },
  { type: 'cmd', answers: ['g++'], meaning: 'GNU C++ 编译器', en: 'GNU C++ compiler', cat: '编译与调试', usage: 'g++ -o app main.cpp' },
  { type: 'cmd', answers: ['clang'], meaning: 'LLVM 编译器', en: 'clang', cat: '编译与调试', usage: 'clang -o app main.c' },
  { type: 'cmd', answers: ['gdb'], meaning: 'GNU 调试器', en: 'GNU debugger', cat: '编译与调试', usage: 'gdb ./app' },
  { type: 'cmd', answers: ['ldd'], meaning: '查看程序动态依赖库', en: 'list dynamic dependencies', cat: '编译与调试', usage: 'ldd /bin/ls' },
  { type: 'cmd', answers: ['nm'], meaning: '查看目标文件符号表', en: 'name list', cat: '编译与调试', usage: 'nm a.out' },
  { type: 'cmd', answers: ['objdump'], meaning: '转储目标文件信息', en: 'object dump', cat: '编译与调试', usage: 'objdump -d a.out' },
  { type: 'cmd', answers: ['readelf'], meaning: '查看 ELF 文件信息', en: 'read ELF', cat: '编译与调试', usage: 'readelf -h a.out' },
  { type: 'cmd', answers: ['strip'], meaning: '剥离二进制中的符号', en: 'strip', cat: '编译与调试', usage: 'strip app' },
  { type: 'cmd', answers: ['ar'], meaning: '创建/管理静态库', en: 'archive', cat: '编译与调试', usage: 'ar rcs lib.a a.o' },

  // ========== 性能监控 ==========
  { type: 'cmd', answers: ['iotop'], meaning: '磁盘 IO 实时监控', en: 'IO top', cat: '性能监控', usage: 'iotop -o' },
  { type: 'cmd', answers: ['iftop'], meaning: '网络流量实时监控', en: 'interface top', cat: '性能监控', usage: 'iftop' },
  { type: 'cmd', answers: ['mpstat'], meaning: '多核 CPU 使用率统计', en: 'multiprocessor statistics', cat: '性能监控', usage: 'mpstat -P ALL 1' },
  { type: 'cmd', answers: ['pidstat'], meaning: '按进程统计资源占用', en: 'PID statistics', cat: '性能监控', usage: 'pidstat 1' },
  { type: 'cmd', answers: ['glances'], meaning: '全能系统监控面板', en: 'glances', cat: '性能监控', usage: 'glances' },
  { type: 'cmd', answers: ['perf'], meaning: 'Linux 性能剖析工具', en: 'performance', cat: '性能监控', usage: 'perf stat ./app' },
  { type: 'cmd', answers: ['nproc'], meaning: '显示 CPU 核数', en: 'number of processors', cat: '性能监控', usage: 'nproc' },
  { type: 'cmd', answers: ['taskset'], meaning: '设置进程 CPU 亲和性', en: 'task set', cat: '性能监控', usage: 'taskset -c 0-3 ./app' },

  // ========== 安全加固 ==========
  { type: 'cmd', answers: ['ssh-keygen'], meaning: '生成 SSH 密钥对', en: 'SSH key generator', cat: '安全加固', usage: 'ssh-keygen -t ed25519' },
  { type: 'cmd', answers: ['ssh-copy-id'], meaning: '把公钥安装到远程主机', en: 'SSH copy ID', cat: '安全加固', usage: 'ssh-copy-id user@host' },
  { type: 'cmd', answers: ['nftables'], meaning: '新一代防火墙框架', en: 'netfilter tables', cat: '安全加固', usage: 'nft list ruleset' },
  { type: 'cmd', answers: ['firewalld'], meaning: '动态防火墙守护进程', en: 'firewall daemon', cat: '安全加固', usage: 'firewall-cmd --list-all' },
  { type: 'cmd', answers: ['auditctl'], meaning: '配置内核审计规则', en: 'audit control', cat: '安全加固', usage: 'auditctl -a always,exit -S open' },
  { type: 'cmd', answers: ['last'], meaning: '查看最近登录历史', en: 'last', cat: '安全加固', usage: 'last -10' },
  { type: 'cmd', answers: ['lastlog'], meaning: '查看每个用户最后登录', en: 'last log', cat: '安全加固', usage: 'lastlog' },
  { type: 'cmd', answers: ['getent'], meaning: '查询系统数据库条目', en: 'get entries', cat: '安全加固', usage: 'getent passwd user' },

  // ========== 网络补充 ==========
  { type: 'cmd', answers: ['whois'], meaning: '域名注册信息查询', en: 'who is', cat: '网络补充', usage: 'whois example.com' },
  { type: 'cmd', answers: ['socat'], meaning: '双向数据通道瑞士军刀', en: 'socket cat', cat: '网络补充', usage: 'socat TCP-LISTEN:8080,fork TCP:web:80' },
  { type: 'cmd', answers: ['iperf3'], meaning: '网络带宽测试工具', en: 'iperf 3', cat: '网络补充', usage: 'iperf3 -c 服务器IP' },
  { type: 'cmd', answers: ['route'], meaning: '查看/操作路由表', en: 'route', cat: '网络补充', usage: 'route -n' },
  { type: 'cmd', answers: ['arp'], meaning: '查看/操作 ARP 缓存', en: 'address resolution protocol', cat: '网络补充', usage: 'arp -a' },
  { type: 'cmd', answers: ['resolvectl'], meaning: 'systemd 的 DNS 解析控制', en: 'resolve control', cat: '网络补充', usage: 'resolvectl status' },
  { type: 'cmd', answers: ['telnet'], meaning: '远程登录（明文，已淘汰）', en: 'telnet', cat: '网络补充', usage: 'telnet host 23' },

  // ========== 文件工具 ==========
  { type: 'cmd', answers: ['mktemp'], meaning: '创建唯一临时文件/目录', en: 'make temp', cat: '文件工具', usage: 'mktemp -d' },
  { type: 'cmd', answers: ['readlink'], meaning: '解析符号链接的真实路径', en: 'read link', cat: '文件工具', usage: 'readlink -f /usr/bin/python' },
  { type: 'cmd', answers: ['rename'], meaning: '批量重命名文件', en: 'rename', cat: '文件工具', usage: 'rename "s/.txt/.md/" *.txt' },
  { type: 'cmd', answers: ['shred'], meaning: '安全擦除文件内容', en: 'shred', cat: '文件工具', usage: 'shred -u secret.txt' },
  { type: 'cmd', answers: ['truncate'], meaning: '把文件调整到指定大小', en: 'truncate', cat: '文件工具', usage: 'truncate -s 10M a.img' },
  { type: 'cmd', answers: ['fallocate'], meaning: '预分配磁盘空间', en: 'fallocate', cat: '文件工具', usage: 'fallocate -l 1G a.img' },
  
  // ========== 系统工具 ==========
  { type: 'cmd', answers: ['timedatectl'], meaning: '查看/设置时间日期与时区', en: 'time date control', cat: '系统工具', usage: 'timedatectl set-timezone Asia/Shanghai' },
  { type: 'cmd', answers: ['hwclock'], meaning: '读写硬件时钟', en: 'hardware clock', cat: '系统工具', usage: 'hwclock --systohc' },
  { type: 'cmd', answers: ['locale'], meaning: '查看/设置语言区域', en: 'locale', cat: '系统工具', usage: 'locale -a' },
  { type: 'cmd', answers: ['lsb_release'], meaning: '显示发行版信息', en: 'LSB release', cat: '系统工具', usage: 'lsb_release -a' },
  { type: 'cmd', answers: ['neofetch'], meaning: '终端系统信息展示', en: 'neofetch', cat: '系统工具', usage: 'neofetch' },
  { type: 'cmd', answers: ['loginctl'], meaning: '管理系统登录会话', en: 'login control', cat: '系统工具', usage: 'loginctl list-sessions' },
  { type: 'cmd', answers: ['arch'], meaning: '显示系统架构', en: 'architecture', cat: '系统工具', usage: 'arch' },

  // ========== 包管理补充 ==========
  { type: 'cmd', answers: ['dnf'], meaning: 'Fedora/RHEL 包管理器', en: 'dnf', cat: '包管理补充', usage: 'dnf install vim' },
  { type: 'cmd', answers: ['zypper'], meaning: 'openSUSE 包管理器', en: 'zypper', cat: '包管理补充', usage: 'zypper install vim' },
  { type: 'cmd', answers: ['brew'], meaning: 'Homebrew 包管理器', en: 'homebrew', cat: '包管理补充', usage: 'brew install wget' },
  { type: 'cmd', answers: ['nix'], meaning: '函数式包管理器', en: 'nix', cat: '包管理补充', usage: 'nix shell nixpkgs#hello' },
  
  // ========== 数据库 ==========
  { type: 'cmd', answers: ['mysql'], meaning: 'MySQL 数据库客户端', en: 'MySQL', cat: '数据库', usage: 'mysql -u root -p' },
  { type: 'cmd', answers: ['psql'], meaning: 'PostgreSQL 数据库客户端', en: 'Postgres SQL', cat: '数据库', usage: 'psql -U user -d dbname' },
  { type: 'cmd', answers: ['sqlite3'], meaning: 'SQLite 轻量数据库客户端', en: 'SQLite 3', cat: '数据库', usage: 'sqlite3 my.db' },
  { type: 'cmd', answers: ['redis-cli'], meaning: 'Redis 客户端', en: 'Redis CLI', cat: '数据库', usage: 'redis-cli ping' },

  // ========== 参数速记补充 ==========
  { type: 'flag', answers: ['--help'], meaning: '显示帮助信息', en: 'help', cat: '参数速记' },
  { type: 'flag', answers: ['--version'], meaning: '显示版本号', en: 'version', cat: '参数速记' },
  { type: 'flag', answers: ['-q'], meaning: '静默模式（少输出）', en: 'quiet', cat: '参数速记' },
  { type: 'flag', answers: ['-z'], meaning: 'gzip 压缩 / 空行分隔', en: 'gzip / zero', cat: '参数速记' },
  { type: 'flag', answers: ['-k'], meaning: '保留 / 保持', en: 'keep', cat: '参数速记' },
  { type: 'flag', answers: ['-j'], meaning: 'bzip2 压缩 / 并行任务数', en: 'bzip2 / jobs', cat: '参数速记' },
  { type: 'flag', answers: ['-L'], meaning: '跟随符号链接', en: 'follow links', cat: '参数速记' },
  { type: 'flag', answers: ['-S'], meaning: '大小写敏感 / 后缀', en: 'sensitive / suffix', cat: '参数速记' },
  { type: 'flag', answers: ['--'], meaning: '选项结束标记（后面都是参数）', en: 'end of options', cat: '参数速记', usage: 'rm -- -weird-file' },
  { type: 'flag', answers: ['-b'], meaning: '字节 / 备份 / 后台', en: 'bytes / backup / background', cat: '参数速记' },
  { type: 'flag', answers: ['-C'], meaning: '目录 / 彩色输出', en: 'directory / color', cat: '参数速记' },
  { type: 'flag', answers: ['-Z'], meaning: '压缩 / 安全上下文', en: 'compress / SELinux context', cat: '参数速记' }
];
